name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'git ref' # refs/tags/v1.0.0
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORK_REF: ${{ github.event.inputs.tag }}"
    steps:
    - uses: actions/checkout@v2
    - name: print GITHUB_WORK_REF
      run: echo $GITHUB_WORK_REF
    - name: Set GRAFANA_VERSION_NUMBER
      run: GRAFANA=`grep 'FROM grafana/grafana' Dockerfile`; echo "GRAFANA_VERSION_NUMBER=${GRAFANA#FROM grafana/grafana:}" >> $GITHUB_ENV
    - name: Set GIT_TAG
      run: echo "GIT_TAG=${GITHUB_WORK_REF#refs/}" >> $GITHUB_ENV
    - name: Set GIT_TAG_VERSION
      run: echo "GIT_TAG_VERSION=${GITHUB_WORK_REF#refs/tags/v}" >> $GITHUB_ENV
    - name: Print GRAFANA_VERSION_NUMBER
      run: echo ${{env.GRAFANA_VERSION_NUMBER}}
    - name: Print GIT_TAG
      run: echo ${{env.GIT_TAG}}
    - name: Print GIT_TAG_VERSION
      run: echo ${{env.GIT_TAG_VERSION}}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        tags: ui3o/grafana-quick-log-panel:${{ env.GRAFANA_VERSION_NUMBER }}-${{ env.GIT_TAG_VERSION }}
        push: true
        build-args: |
          GRAFANA_API_KEY=${{ secrets.GRAFANA_API_KEY }}
          GIT_TAG=${{ env.GIT_TAG }}